[package]
name = "simd"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
simd_macros = { path = "../simd_macros" }

half.workspace = true
zerocopy.workspace = true

[dev-dependencies]
rand.workspace = true

[build-dependencies]
cc = "1.2.22"

[lints]
workspace = true
