[package]
name = "vector"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
distance = { path = "../distance" }
rabitq = { path = "../rabitq" }
simd = { path = "../simd" }

serde.workspace = true

[lints]
workspace = true
