[package]
name = "make"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
object = { version = "0.37.3", default-features = false, features = [
    "read",
    "wasm",
] }
shlex = "1.3.0"
target-triple = "0.1.4"
